FROM oven/bun:latest

WORKDIR /app

# Copy only frontend's package.json and bun.lockb if present
COPY package.json ./

# Copy the rest of the frontend workspace
COPY . .

RUN bun install

EXPOSE 5173
CMD ["bun", "run", "mock", "--host", "0.0.0.0"]
