services:
  
  postgres:
    image: postgres
    container_name: postgres-db
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres-db_data:/var/lib/postgresql/data
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    depends_on:
      - postgres
    restart: unless-stopped
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend_app
    depends_on:
      - postgres
      - redis
    env_file:
      - ./backend/.env.development
    ports:
      - "8080:8080"
      - "5005:5005"
    restart: unless-stopped
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.local
    container_name: frontend_app
    env_file:
      - ./frontend/.env.development
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    restart: unless-stopped

volumes:
  postgres-db_data:
