services:
  postgres:
    image: postgres
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: avian_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
    ports:
      - "5432:5432"
    volumes:
      - postgres-db_data:/var/lib/postgresql/data
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_app
    depends_on:
      - postgres
    env_file:
      - ./backend/.env
      - ./backend/.env.local
    ports:
      - "8080:8080"
      - "5005:5005"
    restart: unless-stopped
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.local
    container_name: frontend_app
    env_file:
      - ./frontend/.env
      - ./frontend/.env.local
    ports:
      - "5173:5173"
    restart: unless-stopped

volumes:
  postgres-db_data:
