services:
  postgres:
    image: postgres
    container_name: postgres-db
    env_file:
      - .env.development
      - .env.development.local
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres-db_data:/var/lib/postgresql/data
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: backend_app
    depends_on:
      - postgres
    env_file:
      - .env.development
      - .env.development.local
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${DATABASE_NAME}
      SPRING_DATASOURCE_USERNAME: ${DATABASE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DATABASE_PASSWORD}
      FRONTEND_URL: ${FRONTEND_URL}
      SPRING_PROFILES_ACTIVE: ${MODE}
    ports:
      - "8080:8080"
      - "5005:5005"
    restart: unless-stopped
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.development
    container_name: frontend_app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    restart: unless-stopped
    env_file:
      - .env.development
      - .env.development.local
    environment:
      VITE_BACKEND_URL: ${BACKEND_URL}

volumes:
  postgres-db_data:
