services:
  postgres:
    image: postgres
    container_name: postgres-db
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    restart: always
    ports:
      - "5432:5432"
    volumes:
     - postgres-db_data:/var/lib/postgresql/data  
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    depends_on:
      - postgres
    restart: unless-stopped
  backend:
    build: ./backend
    container_name: backend_app
    depends_on:
      - postgres
      - redis
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${DATABASE_NAME}
      SPRING_DATASOURCE_USERNAME: ${DATABASE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DATABASE_PASSWORD}
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      SPRING_PROFILES_ACTIVE: local
    command: ["mvn", "spring-boot:run"]
    ports:
      - "8080:8080"
      - "5005:5005"
    restart: unless-stopped
  frontend:
    build: ./frontend
    container_name: frontend_app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    restart: unless-stopped
    environment:
      - BUN_DEV_SERVER_HOST=0.0.0.0 
    command: ["bun", "run", "dev", "--host", "0.0.0.0"]

volumes:
   postgres-db_data:


   