databases:
  - name: avian-db
    databaseName: avian_db
    user: avian_user
    plan: free

services:
  - name: backend
    type: web
    runtime: docker
    rootDir: backend
    dockerfilePath: Dockerfile
    envVars:
      - key: DATABASE_NAME
        value: avian_db
      - key: DATABASE_USERNAME
        value: avian_user
      - key: DATABASE_PASSWORD
        sync: false
      - key: SPRING_PROFILES_ACTIVE
        value: development
      - key: FRONTEND_URL
        sync: false
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
    plan: free
    autoDeploy: true

  - name: frontend
    type: web
    runtime: docker
    rootDir: frontend
    dockerfilePath: Dockerfile.development
    envVars:
      - key: VITE_BACKEND_URL
        sync: false
    plan: free
    autoDeploy: true

