services:
  postgres:
    image: postgres
    container_name: postgres-db
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    restart: always
    ports:
      - "5432:5432"
    volumes:
     - postgres-db_data:/var/lib/postgresql/data  
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
   postgres-db_data:


   