spring:
  redis:
    host: ${SPRING_REDIS_HOST}
    port: ${SPRING_REDIS_PORT}

  session:
    store-type: redis

logging:
  level:
    org:
      springframework.security: TRACE

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

