logging:
  level:
    org:
      springframework.security: DEBUG
spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        generate_statistics: true
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

