spring:
  cloud:
    aws:
      region:
        static: ap-southeast-2
      credentials:
        access-key: ${AWS_ACCESS_KEY_ID}
        secret-key: ${AWS_SECRET_ACCESS_KEY}
app:
  s3:
    bucket: prod-bucket