name: Commit-Message

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Commit-Message:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Lint last commit message
        run: |
          bun x commitlint --from ${{ github.event.pull_request.base.sha }} --to HEAD