name: Format

on: 
  push:
    branches:
      - main
  pull_request:

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install OpenJDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      - name: Format Java code with google-java-format
        run: java -jar tools/google-java-format-1.22.0-all-deps.jar --dry-run --set-exit-if-changed $(find . -name '*.java')
        working-directory: backend

      - name: Install frontend dependencies
        run: bun install
        working-directory: frontend

      - name: Run frontend format check
        run: bun x prettier --check "src/**/*.{ts,tsx}"
        working-directory: frontend