name: Format

on: 
  push:
    branches:
      - main
  pull_request:


jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install
        working-directory: frontend

      - name: Run frontend format check
        run: bun x prettier --check "src/**/*.{ts,tsx}"
        working-directory: frontend